#!/usr/bin/env php
<?php

require ('./config.php');

if (!ini_get('ibm_db2.instance_name'))
{
	echo "ibm_db2.instance_name not set in php.ini\n";
	exit(1);
}

if ($argc != 2)
{
	echo "Usage: group_imp GROUP-FILE\n";
	echo "   GROUP-FILE        group file\n";
	exit(1);
}

if (!file_exists($argv[1]))
{
	echo "$argv[1] does not exist!\n";
	exit(1);
}

if (!is_readable($argv[1]))
{
	echo "$argv[1] is not readable!\n";
	exit(1);
}

$handle = fopen($argv[1], "r");

while (!feof($handle))
{
	$line = fgets($handle, 1024);

	if ($line)
		list($groupname, $users) = explode(":", $line);

	if ($groupname != '')
	{
		$users = substr($users, 1);
		if (substr($users, -1) == "\n")
			$users = substr($users, 0, -1);

		$ar["$groupname"] = explode(" ", $users);
	}
}

fclose($handle);

$conn = db2_connect($dbname, $dbuser, $dbpwd);

echo "\nImporting groups into table '$grouptable' in database '$dbname'\n\n";

$i = 0;
$ni = 0;

foreach ($ar as $groupname => $users)
{
	foreach ($users as $username)
	{
		$insert = "insert into $grouptable ($namefield, $groupfield) values ('$username', '$groupname')";
		$res = @db2_exec($conn, $insert);

		if ($res != FALSE)
		{
			echo "User '$username' in group '$groupname' imported.\n";
			$i++;
		}
		else
		{
			echo "User '$username' in group '$groupname' NOT imported.\n";
			$ni++;
		}
	}
}

echo "\n";
echo "Users/Groups imported: $i\n";
echo "Users/Groups rejected: $ni\n";
echo "\n";

if ($ni > 0)
	exit(2);
else
	exit(0);

?>
