#!/usr/bin/env php
<?php

require ('./config.php');

if (!ini_get('ibm_db2.instance_name'))
{
	echo "ibm_db2.instance_name not set in php.ini\n";
	exit(1);
}

$handle = fopen("/etc/shadow", "r");

while (!feof($handle))
{
	$line = fgets($handle, 512);

	if ($line)
		list($username, $password) = explode(":", $line);

	if ($username != '' && $username != 'root' && $password != '*' && $password != '!!')
	{
		$arr["$username"] = $password;
	}
}

fclose($handle);

$conn = db2_connect($dbname, $dbuser, $dbpwd);

echo "\nImporting users into table '$usertable' in database '$dbname'\n\n";

$i = 0;
$ni = 0;

foreach ($arr as $u => $p)
{
	$insert = "insert into $usertable ($namefield, $passwordfield) values ('$u', '$p')";
	$res = @db2_exec($conn, $insert);

	if ($res != FALSE)
	{
		echo "User $u imported.\n";
		$i++;
	}
	else
	{
		echo "User $u NOT imported.\n";
		$ni++;
	}
}

echo "\n";
echo "Users imported: $i\n";
echo "Users rejected: $ni\n";
echo "\n";

if ($ni > 0)
	exit(2);
else
	exit(0);

?>
